### ISSUE TITLE
plugin_iriscontrol  html/template: "index.html" is undefined

### ISSUE THREAD

**Issue by shuyabin** [iris-contrib/examples#12]
Hello ,  i have run  plugin_iriscontrol  example but  error 
![image](https://cloud.githubusercontent.com/assets/14884581/19618577/4f5403c0-9881-11e6-9a83-622d34b13d67.png)

i have install  github.com/kataras/go-template/html

**Comment by kataras** [comment]
Hello @shuyabin ,

I just ran it from a clean install (windows virtual box)
and the page is rendering correctly.

I think your issue is that maybe you don't have access to your `$myuser/.iris` folder? (the iris-control assets are downloaded in that location at the first 'boot' time)

Please give us more information, like your operating system, the iris version and so on

Thanks,
kataras

**Comment by shuyabin** [comment]
Hello @kataras    my   iris version   is 4.5.0     operating system  Winowds 10    
 I've been looking for  html/templates  index.html , but  No find .
![image](https://cloud.githubusercontent.com/assets/14884581/19882795/1e3e74ba-a04b-11e6-8627-d98168eb924f.png)

![image](https://cloud.githubusercontent.com/assets/14884581/19882799/2914b386-a04b-11e6-9c9a-9f3bc2ae68ff.png)


Thank you for your help
shuyabin

**Comment by kataras** [comment]
Go to `C:\Users\$yourname\.iris` and check if files are there or not, templates should downloaded when you first run the iris control plugin... if not then you did something wrong or you don't have permission. Let me know in order to give you the link to download them manually
