### ISSUE TITLE
JWT token generation for Iris v7 example

### ISSUE THREAD

**Issue by threestarsgenius** [iris-contrib/examples#15]
Is there any example with JWT tokens for Iris v7?

I've found this one https://github.com/iris-contrib/middleware/blob/master/jwt/_example/main.go (for Iris v6)

**Comment by kataras** [comment]
@threestarsgenius Hello, sorry for being late to answer but I was coding the [SetImmutable](https://github.com/iris-contrib/community-board/issues/5) feature among others. There are some commits and prs by community on iris-contrib/middleware/jwt, you can take a look there. JWT is not supported by me because I don't trust it and I don't recommend this for any web developer. Use sessions whenever you can but if you really need to use JWT you can use any third-party library, you have access to http.ResponseWriter with `ctx.ResponseWriter()` and *http.Request with `ctx.Request()

**Comment by kataras** [comment]
@threestarsgenius Hello, sorry for being late to answer but I was coding the [SetImmutable](https://github.com/iris-contrib/community-board/issues/5) feature among others. There are some commits and prs by community on iris-contrib/middleware/jwt as you noticed, you can take a look at therir code. JWT is not supported by me because I don't trust it and I don't recommend this for any web developer. Use sessions whenever you can but if you really need to use JWT you can use any third-party library, you have access to http.ResponseWriter with `ctx.ResponseWriter()` and *http.Request with `ctx.Request()`

**Comment by kataras** [comment]
@threestarsgenius Hello, sorry for being late to answer but I was coding the [SetImmutable](https://github.com/iris-contrib/community-board/issues/5) feature among others. There are some commits and prs by community on iris-contrib/middleware/jwt as you noticed, you can take a look at their code. JWT is not supported by me because I don't trust it and I don't recommend this for any web developer. Use sessions whenever you can but if you really need to use JWT you can use any third-party library, you have access to http.ResponseWriter with `ctx.ResponseWriter()` and *http.Request with `ctx.Request()`

**Comment by kataras** [comment]
@threestarsgenius Hello, sorry for being late to answer but I was coding the [SetImmutable](https://github.com/iris-contrib/community-board/issues/5) feature among others. There are some commits and prs by community on iris-contrib/middleware/jwt as you noticed, you can take a look at their code. JWT is not supported by me and it is not inside kataras/iris/middleware because I don't trust it and I don't recommend this for any web developer. Use sessions whenever you can but if you really need to use JWT you can use any third-party library, you have access to http.ResponseWriter with `ctx.ResponseWriter()` and *http.Request with `ctx.Request()`

**Comment by kataras** [comment]
You could use OAuth2 too, I pushed an updated example today [here](https://github.com/kataras/iris/blob/master/_examples/intermediate/oauth2/main.go)

**Comment by kataras** [comment]
You could use OAuth2 too, I pushed an updated example earlier today [here](https://github.com/kataras/iris/blob/master/_examples/intermediate/oauth2/main.go), please let me know if my answers helped you or not

**Comment by threestarsgenius** [comment]
@kataras , thanks for your quick reply. Unfortunately OAuth2 for me is not a solution. I'll probably use some third-party library as you've suggested.

But if you'll have some time in future would be great to see example with JWT tokens and Iris for latest version :)

**Comment by kataras** [comment]
I did it, look the changes in order to understand how easy the conversion from v6 to v7 was :)

**Comment by kataras** [comment]
You're welcome, I did it, look the changes in order to understand how easy the conversion from v6 to v7 was :) 

Inside the[jwt/_example](https://github.com/iris-contrib/middleware/tree/master/jwt/_example) folder you'll see the example for iris v7.

Please star or watch the repositories that you're interesting in order to receive updates( i.e the kataras/iris, iris-contrib/examples and iris-contrib/middleware)

**Comment by threestarsgenius** [comment]
@kataras thanks a lot!! Just have one thing to fix in this [merge request](https://github.com/iris-contrib/middleware/pull/29/files).

P.S. May I'll extend that example to be understandable for other guys which aren't familiar with JWT?

**Comment by kataras** [comment]
Yes you can do that, do what ever you think is better for all users, you 're awesome!

**Comment by kataras** [comment]
@threestarsgenius  Yes you can do that, do what ever you think is better for all users, you 're awesome!

**Comment by threestarsgenius** [comment]
@kataras thanks! I guess you can close this issue :)

**Comment by kataras** [comment]
Its soon, many people may want JWT ( I don't know why but...) help, so I let it open until you push the example code you mentioned before, in order to be able to link that PR with this opened issue and users will be notified (it can be done with "closed" issue too, but closed means "finished" :P )
