### ISSUE TITLE
How to print Session value in Template

### ISSUE THREAD

**Issue by rebootcode** [iris-contrib/examples#24]
I am planning to save user-info from database in session and than printing the name and other value on header template.

Like `Welcome Iris | Logout`

Running query everytime looks bad idea, so I prefer to store the value in session and print them in template.

While I do, `ctx.ViewData("user", user)`  // Where user is struct against user table.

But as soon as I print them, I get "is not a method but has arguments"

**Comment by esemplastic** [comment]
Yes @rebootcode  because you're trying to use a template function instead of printing something, in golang we use the `{{.property_name}}` to print a binded value. Even the Iris' README.md overview html and go source code shows that-- https://github.com/kataras/iris/blob/master/README.md#-installation.

See the first dot(**.**)
```go
Welcome {{.user.Name}} 
```

A trivial example:

./main.go
```go
package main

import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/sessions"
)

type User struct {
	ID   int64
	Name string
}

func main() {
	app := iris.New()
	app.RegisterView(iris.HTML("./views", ".html"))
	sess := sessions.New(sessions.Config{Cookie: "sessionid"})

	app.Get("/login", func(ctx iris.Context) {
		var testUser = User{Name: "iris"}

		session := sess.Start(ctx)
		session.Set("user", testUser)
	})

	app.Get("/", func(ctx iris.Context) {
		session := sess.Start(ctx)
		testUser := session.Get("user")
		ctx.ViewData("user", testUser)
		ctx.View("index.html")
	})

	app.Run(iris.Addr(":8080"))
}
```
./views/index.html
```html
<html>

<head>
    <title>Welcome {{.user.Name}}</title>
</head>

<body>
    <h1>Welcome {{.user.Name}} | Logout
</body>

</html>
```

1. http://localhost:8080/login
2. http://localhost:8080/
